// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wolf.ManagerService.Domain.Repository;

namespace Wolf.ManagerService.Domain.Repository.Migrations
{
    [DbContext(typeof(ManagerDbContext))]
    partial class ManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Wolf.ManagerService.Domain.AggregatesModel.AdminLoginRecords", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("char(36)")
                        .HasMaxLength(36);

                    b.Property<Guid>("Appid")
                        .HasColumnName("appid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ip")
                        .HasColumnName("ip")
                        .HasColumnType("varchar(15) CHARACTER SET utf8mb4")
                        .HasMaxLength(15);

                    b.Property<string>("UserAgent")
                        .HasColumnName("user_agent")
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("char(36)")
                        .HasMaxLength(36);

                    b.HasKey("Id");

                    b.ToTable("admin_login_records");
                });

            modelBuilder.Entity("Wolf.ManagerService.Domain.AggregatesModel.AdminRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Appid")
                        .HasColumnName("appid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnName("role_id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("admin_roles");
                });

            modelBuilder.Entity("Wolf.ManagerService.Domain.AggregatesModel.Admins", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("char(36)")
                        .HasMaxLength(36);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnName("account")
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4")
                        .HasMaxLength(30);

                    b.Property<DateTimeOffset?>("ForbitTime")
                        .HasColumnName("forbit_time")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("LastUpdateTime")
                        .HasColumnName("last_update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnName("password_salt")
                        .HasColumnType("varchar(6) CHARACTER SET utf8mb4")
                        .HasMaxLength(6);

                    b.Property<string>("RealName")
                        .HasColumnName("real_name")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<DateTimeOffset>("RegisterTime")
                        .HasColumnName("register_time")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserState")
                        .HasColumnName("user_state")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("admin");
                });

            modelBuilder.Entity("Wolf.ManagerService.Domain.AggregatesModel.Applications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AddUserId")
                        .HasColumnName("add_user_id")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EditUserId")
                        .HasColumnName("edit_user_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<bool>("State")
                        .HasColumnName("state")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Summary")
                        .HasColumnName("summary")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnName("update_time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("applications");
                });

            modelBuilder.Entity("Wolf.ManagerService.Domain.AggregatesModel.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Appid")
                        .HasColumnName("appid")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnName("create_time")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreateUserId")
                        .HasColumnName("create_user_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<bool>("State")
                        .HasColumnName("state")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Summary")
                        .HasColumnName("summary")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnName("update_time")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdateUserId")
                        .HasColumnName("update_user_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });
#pragma warning restore 612, 618
        }
    }
}
